"""
Stitch → Godot Scaffold Tool

Takes a Stitch-generated HTML file and auto-generates:
1. The C# bridge class (CefTexture loading, IPC handlers, fallback UI)
2. A .tscn scene file
3. GameManager registration snippet

Usage:
  python stitch_scaffold.py <html_file> <screen_name> [--buttons btn1,btn2,btn3]

Example:
  python stitch_scaffold.py ui/debrief/index.html DebriefScreen --buttons play-again,return-to-menu,save-suit

Or auto-detect buttons from the HTML:
  python stitch_scaffold.py ui/debrief/index.html DebriefScreen --auto

Output:
  Scripts/UI/<ScreenName>.cs
  Scenes/<ScreenName>.tscn
  Prints GameManager registration code to paste
"""

import argparse
import os
import re
import sys
from pathlib import Path

# Project root
GODOT_TD = Path(__file__).parent.parent

def find_buttons_in_html(html_path: str) -> list[str]:
    """Scan HTML for interactive elements that would send IPC messages."""
    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    buttons = []

    # Find onclick handlers, data-action attributes, button IDs
    # Pattern: onclick="...someAction..."  or  data-action="something"  or  id="some-button"
    for match in re.finditer(r'data-action=["\']([^"\']+)["\']', html):
        buttons.append(match.group(1))

    for match in re.finditer(r'id=["\']([^"\']*(?:btn|button|action|select|launch|start|back|confirm|cancel)[^"\']*)["\']', html, re.IGNORECASE):
        buttons.append(match.group(1))

    # Look for cefQuery or postMessage patterns
    for match in re.finditer(r'cefQuery\(\{[^}]*request:\s*["\'](\w+)', html):
        buttons.append(match.group(1))

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for b in buttons:
        if b not in seen:
            seen.add(b)
            unique.append(b)

    return unique


def to_pascal_case(kebab: str) -> str:
    """Convert kebab-case or snake_case to PascalCase."""
    return ''.join(word.capitalize() for word in re.split(r'[-_]', kebab))


def to_camel_case(kebab: str) -> str:
    """Convert kebab-case to camelCase."""
    parts = re.split(r'[-_]', kebab)
    return parts[0].lower() + ''.join(word.capitalize() for word in parts[1:])


def generate_cs(screen_name: str, html_rel_path: str, buttons: list[str]) -> str:
    """Generate the C# bridge class."""

    # Build IPC handler cases
    ipc_cases = ""
    for btn in buttons:
        method_name = f"On{to_pascal_case(btn)}"
        ipc_cases += f'                case "{btn}":\n'
        ipc_cases += f'                    {method_name}();\n'
        ipc_cases += f'                    break;\n'

    # Build handler methods
    handler_methods = ""
    for btn in buttons:
        method_name = f"On{to_pascal_case(btn)}"
        handler_methods += f"""
        private void {method_name}()
        {{
            GD.Print("[{screen_name}] {btn} pressed");
            // TODO: implement {btn} action
        }}
"""

    # Build fallback buttons
    fallback_buttons = ""
    for btn in buttons:
        label = btn.replace('-', ' ').replace('_', ' ').title()
        fallback_buttons += f"""
            var {to_camel_case(btn)}Btn = new Button();
            {to_camel_case(btn)}Btn.Text = "{label}";
            {to_camel_case(btn)}Btn.CustomMinimumSize = new Vector2(200, 45);
            {to_camel_case(btn)}Btn.AddThemeFontSizeOverride("font_size", 16);
            {to_camel_case(btn)}Btn.Pressed += () => On{to_pascal_case(btn)}();
            vbox.AddChild({to_camel_case(btn)}Btn);
"""

    return f"""using Godot;

namespace JunkyardTD
{{
    /// <summary>
    /// {screen_name} — renders Stitch-designed HTML UI via godot-cef.
    /// Falls back to native Godot UI if CEF is not available.
    /// Auto-generated by stitch_scaffold.py
    /// </summary>
    public partial class {screen_name} : Control
    {{
        private GodotObject _cefTexture;
        private Label _statusLabel;
        private bool _launched;

        private const string HTML_PATH = "res://{html_rel_path}";

        public override void _Ready()
        {{
            // Status label for debugging
            _statusLabel = new Label();
            _statusLabel.SetAnchorsPreset(LayoutPreset.BottomLeft);
            _statusLabel.Position = new Vector2(10, -30);
            _statusLabel.AddThemeColorOverride("font_color", new Color(0.5f, 0.7f, 1f, 0.6f));
            AddChild(_statusLabel);

            if (!ClassDB.ClassExists("CefTexture"))
            {{
                SetStatus("godot-cef not found — using fallback UI");
                BuildFallbackUI();
                return;
            }}

            LaunchCef();
        }}

        private void LaunchCef()
        {{
            try
            {{
                _cefTexture = ClassDB.Instantiate("CefTexture").AsGodotObject();
                if (_cefTexture == null)
                {{
                    SetStatus("Failed to create CefTexture");
                    BuildFallbackUI();
                    return;
                }}

                // Configure CEF
                var size = GetViewportRect().Size;
                _cefTexture.Call("set_size", (int)size.X, (int)size.Y);

                // Create TextureRect to display the browser
                var textureRect = new TextureRect();
                textureRect.SetAnchorsPreset(LayoutPreset.FullRect);
                textureRect.StretchMode = TextureRect.StretchModeEnum.Scale;
                textureRect.Texture = _cefTexture.Call("get_texture").As<Texture2D>();
                AddChild(textureRect);

                // Connect IPC
                _cefTexture.Connect("on_ipc_message", Callable.From<string, string>(_OnIpcMessage));
                _cefTexture.Connect("on_console_message", Callable.From<int, string, string, int>(OnConsoleMessage));

                // Load the HTML
                string absPath = ProjectSettings.GlobalizePath(HTML_PATH);
                _cefTexture.Call("load_url", "file:///" + absPath.Replace("\\\\", "/"));

                SetStatus("Stitch UI loading...");
            }}
            catch (System.Exception ex)
            {{
                GD.PrintErr($"[{screen_name}] CEF failed: {{ex.Message}}");
                BuildFallbackUI();
            }}
        }}

        private void _OnIpcMessage(string name, string payload)
        {{
            GD.Print($"[{screen_name}] IPC: {{name}} = {{payload}}");

            switch (name)
            {{
                case "ready":
                    GD.Print("[{screen_name}] Stitch UI ready");
                    break;
{ipc_cases}
                default:
                    GD.Print($"[{screen_name}] Unknown IPC: {{name}}");
                    break;
            }}
        }}
{handler_methods}
        private void OnConsoleMessage(int level, string message, string source, int line)
        {{
            string levelStr = level switch {{ 0 => "DBG", 1 => "INF", 2 => "WRN", 3 => "ERR", _ => "LOG" }};
            GD.Print($"[CEF {{levelStr}}] {{message}}");
        }}

        private void BuildFallbackUI()
        {{
            var bg = new ColorRect();
            bg.SetAnchorsPreset(LayoutPreset.FullRect);
            bg.Color = new Color(0.04f, 0.06f, 0.12f);
            AddChild(bg);

            var center = new CenterContainer();
            center.SetAnchorsPreset(LayoutPreset.FullRect);
            AddChild(center);

            var vbox = new VBoxContainer();
            vbox.AddThemeConstantOverride("separation", 16);
            center.AddChild(vbox);

            var title = new Label();
            title.Text = "{screen_name.replace('Screen', '').upper()}";
            title.HorizontalAlignment = HorizontalAlignment.Center;
            title.AddThemeFontSizeOverride("font_size", 36);
            title.AddThemeColorOverride("font_color", new Color(0.5f, 0.9f, 1f));
            vbox.AddChild(title);

            var subtitle = new Label();
            subtitle.Text = "CEF not available — fallback UI";
            subtitle.HorizontalAlignment = HorizontalAlignment.Center;
            subtitle.AddThemeFontSizeOverride("font_size", 14);
            subtitle.AddThemeColorOverride("font_color", new Color(0.5f, 0.5f, 0.5f));
            vbox.AddChild(subtitle);
{fallback_buttons}
        }}

        private void SetStatus(string text)
        {{
            if (_statusLabel != null)
                _statusLabel.Text = text;
            GD.Print($"[{screen_name}] {{text}}");
        }}
    }}
}}
"""


def generate_tscn(screen_name: str) -> str:
    """Generate a minimal .tscn scene file."""
    return f"""[gd_scene format=3]

[node name="{screen_name}" type="Control"]
layout_mode = 3
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
script = ExtResource("res://Scripts/UI/{screen_name}.cs")
"""


def main():
    parser = argparse.ArgumentParser(description="Scaffold a Godot UI screen from Stitch HTML")
    parser.add_argument("html_file", help="Path to the Stitch HTML file (relative to Godot_TD/)")
    parser.add_argument("screen_name", help="C# class name (e.g., DebriefScreen)")
    parser.add_argument("--buttons", help="Comma-separated button/action IDs", default="")
    parser.add_argument("--auto", action="store_true", help="Auto-detect buttons from HTML")
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing files")
    args = parser.parse_args()

    html_path = GODOT_TD / args.html_file
    if not html_path.exists():
        print(f"WARNING: HTML file not found: {html_path}")
        print("(Generating scaffold anyway — create the HTML file later)")

    # Get buttons
    buttons = []
    if args.auto and html_path.exists():
        buttons = find_buttons_in_html(str(html_path))
        print(f"Auto-detected {len(buttons)} buttons: {buttons}")
    elif args.buttons:
        buttons = [b.strip() for b in args.buttons.split(",")]

    if not buttons:
        buttons = ["back", "confirm"]
        print(f"No buttons specified, using defaults: {buttons}")

    # Generate files
    cs_content = generate_cs(args.screen_name, args.html_file, buttons)
    tscn_content = generate_tscn(args.screen_name)

    cs_path = GODOT_TD / "Scripts" / "UI" / f"{args.screen_name}.cs"
    tscn_path = GODOT_TD / "Scenes" / f"{args.screen_name}.tscn"

    if args.dry_run:
        print("=== C# CLASS ===")
        print(cs_content)
        print("\n=== SCENE FILE ===")
        print(tscn_content)
    else:
        cs_path.parent.mkdir(parents=True, exist_ok=True)
        tscn_path.parent.mkdir(parents=True, exist_ok=True)

        cs_path.write_text(cs_content, encoding='utf-8')
        print(f"Created: {cs_path}")

        tscn_path.write_text(tscn_content, encoding='utf-8')
        print(f"Created: {tscn_path}")

    # Print registration snippet
    print(f"""
=== Add to Constants.cs ===
public const string SCENE_{args.screen_name.upper()} = "res://Scenes/{args.screen_name}.tscn";

=== Add to GameManager.cs ===
public void Show{args.screen_name.replace('Screen', '')}()
{{
    GetTree().ChangeSceneToFile(Constants.SCENE_{args.screen_name.upper()});
}}
""")


if __name__ == "__main__":
    main()
